[development]
# Development environment settings
DEBUG = true
PORT = 5432
HOST = "localhost"
USER = "postgres"
DATABASE = "postgres"

[global]
# Global variables accessible across environments
APP_NAME = "DPM"
